{% set name = "ratarmount" %}
{% set version = "1.2.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4e529430f38d6a64ec13feab080ff19a1709d131a54c370bb2ee5f14531dc80e
  folder: .

build:
  entry_points:
    - ratarmount=ratarmount.cli:cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=46.4.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - ratarmountcore >=0.10,<0.11
    - mfusepy >=3.0,<4.0
    - rich
    - rich-argparse
    # Optional dependencies for ratarmountcore, which should be constrained exactly as ratarmountcore.
    - indexed_gzip >=1.6.3,<2
    - indexed_zstd >=1.3.1,<2
    - rapidgzip >=0.15,<0.16
    - py7zr >=1.0,<2
    - python-libarchive-c >=5.1,<6
    - python-xz >=0.4,<0.5
    - rarfile >=4,<5
    - pygit2
    - fsspec
    # Last update 5 years ago.
    #- dropboxdrivefs
    - ipfsspec
    - s3fs
    - smbprotocol
    - webdav4

test:
  imports:
    - ratarmount
  commands:
    - pip check
    - ratarmount --help
    - ratarmount --version
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mxmlnkn/ratarmount
  summary: Random Access Read-Only Tar Mount
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ap--
    - mxmlnkn
